name: Azure OIDC Key Vault Sample

on: [workflow_dispatch]

permissions: 
  contents: read
  id-token: write

jobs:
  job:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION }}
      
      - name: Get secret from Key Vault
        id: keyvault-secrets
        run: |
          mysecret=$(az keyvault secret show --name MySecret --vault-name rs-github-secrets --query value -o tsv)
          echo "::add-mask::$mysecret"
          echo "secret-value=$mysecret" >> $GITHUB_OUTPUT

      - name: Use secret
        run: |
          echo "The secret is: ${{ steps.keyvault-secrets.outputs.secret-value }}"

      - name: Update secret
        run: |
          az keyvault secret set --name MySecret --vault-name rs-github-secrets --value SomeVerySecretValueFromActions