name: Beispiel CI/CD für .NET

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - README.md

  workflow_dispatch: 

env:
  Configuration: Release
  DistFolder: ./dist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
            
      - name: Kompilieren der Applikation
        run: |
          dotnet build -c ${{ env.Configuration }}

      - name: Publizieren der Applikation
        run: |
          dotnet publish -c ${{ env.Configuration }} -o ${{ env.DistFolder }} --no-build
      
      - name: Publizieren des Artefakts
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.DistFolder }}
          name: ${{ vars.ARTIFACTNAME }}
  
  deploy-dev:
    needs: build
    uses: ./.github/workflows/reusable-deployment.yaml
    with:
      environment: Dev
      artifact-name: ${{ vars.ARTIFACTNAME }}
      app-name: HelloWorld

  deploy-test:
    needs: deploy-dev
    uses: ./.github/workflows/reusable-deployment.yaml
    with:
      environment: Test
      artifact-name: ${{ vars.ARTIFACTNAME }}
      app-name: HelloWorld

  deploy-prod:
    needs: deploy-test
    uses: ./.github/workflows/reusable-deployment.yaml
    with:
      environment: Prod
      artifact-name: ${{ vars.ARTIFACTNAME }}
      app-name: HelloWorld