name: Environment Sample

on: [workflow_dispatch]

env:
  ARTIFACT_NAME: app
  
jobs:
  dev-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build application
        run: echo "This is my app!" >> app.txt
      
      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.ARTIFACT_NAME }}.txt
          name: ${{ env.ARTIFACT_NAME }}

  test-job:
    needs: dev-job
    uses: ./.github/workflows/deploy-job.yml
    with:
      environment: Test
      artifact-name: ${{ env.ARTIFACT_NAME }}
    secrets: inherit
  
  prod-job:
    needs: test-job
    uses: ./.github/workflows/deploy-job.yml
    with:
      environment: Prod
      artifact-name: ${{ env.ARTIFACT_NAME }}
    secrets: inherit
