name: Einfacher Hallo-Welt Workflow

run-name: Gestartet durch ${{ github.event.issue && format('Issue {0}', github.event.issue.number) || github.actor }}

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person, die gegrüßt werden soll'
        type: string
        default: Welt
      begruessung:
        description: 'Zu verwendende Begrüßung'
        type: string
        default: Hallo

  issues:
    types: [ opened ]

jobs:
  hallo:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      # Entweder run (Skripte/Kommandozeilen) oder uses (Actions)
      - run: echo "$GREETING, $NAME!"
        name: Sag Hallo
        env:
          GREETING: ${{ inputs.begruessung || 'Hallo' }}
          NAME: ${{ inputs.name || 'Welt' }}

      - run: echo "Das aktuelle Arbeitsverzeichnis ist ${{ github.workspace }}"
        name: Zeige Arbeitsverzeichnis an

      - name: Zeige Issue informationen an
        if: github.event.issue
        run: |
          echo "Issue-Titel: $TITLE"
          echo "Issue-Body: $BODY"
        env:
          TITLE: ${{ github.event.issue.title }}
          BODY: ${{ github.event.issue.body || '<Kein Body vorhanden>' }}

      - name: Erzeuge Issue Kommentar
        if: github.event.issue
        run: |
          gh issue comment ${{ github.event.issue.number }} -R ${{ github.repository }} -b "Herzlich Willkommen bei GitHub Actions! Vielen Dank für die Erstellung des Issues, wir kümmern uns schnellstmöglich!"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Erzeuge Issue Kommentar (API)
        if: github.event.issue
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d '{"body":"Kommentar über die API"}'