name: Einfacher Hallo-Welt Workflow

run-name: ${{ github.actor }} hat den Workflow gestartet

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person, die gegrüßt werden soll'
        type: string
        default: Welt
      begruessung:
        description: 'Zu verwendende Begrüßung'
        type: string
        default: Hallo

  issues:
    types: [ opened ]

jobs:
  hallo:
    runs-on: ubuntu-latest
    steps:
      # Entweder run (Skripte/Kommandozeilen) oder uses (Actions)
      - run: echo "$GREETING, $NAME!"
        name: Sag Hallo
        env:
          GREETING: ${{ inputs.begruessung || 'Hallo' }}
          NAME: ${{ inputs.name || 'Welt' }}

      - run: echo "Das aktuelle Arbeitsverzeichnis ist ${{ github.workspace }}"
        name: Zeige Arbeitsverzeichnis an

      - name: Zeige Issue informationen an
        if: github.event.issue
        run: |
          echo "Issue-Titel: $TITLE"
          echo "Issue-Body: $BODY"
        env:
          TITLE: ${{ github.event.issue.title }}
          BODY: ${{ github.event.issue.body }}