name: Multiple jobs and matrix jobs

on: [ workflow_dispatch ]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step in first job
        run: echo "This is the first job"
  
  first-job-in-parallel:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Step in second job
        run: echo "This runs in parallel with the third job"

  second-job-in-parallel:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Step in third job
        run: echo "This runs in parallel with the second job"

  final-job:
    needs: [ first-job-in-parallel, second-job-in-parallel ]
    runs-on: ubuntu-latest
    steps:
      - name: Step in final job
        run: echo "This runs last"