name: Starter Workflow

run-name: Hey ${{ github.actor }}, you are using GitHub Actions!

on:
  workflow_dispatch:

  issues:
    types: [opened]

jobs:
  starter-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to ${{ github.actor }}
        run: echo "Hello, $NAME"
        env:
          NAME: ${{ github.actor }}