name: Starter Workflow

run-name: Hey ${{ github.actor }}, you are using GitHub Actions!

on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        type: string
        description: Who should I greet?
        default: world

  issues:
    types: [opened]

jobs:
  starter-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to ${{ inputs.who-to-greet }}
        run: echo "Hello, $NAME"
        env:
          NAME: ${{ inputs.who-to-greet }}
      
      - name: Add greeting to issue
        if: github.event.issue
        run: |
          gh issue comment ${{ github.event.issue.number }} -R ${{ github.repository_owner }}/${{ github.repository }} -b "Hello from GitHub Actions! Thank you for opening this issue! 🎖️"
        env:
          GITHUB_TOKEN: ${{ github.token }}